absl-py==1.1.0
astor==0.8.1
click==8.1.3
cloudpickle==1.3.0
cycler==0.11.0
dill==0.3.5.1
future==0.18.2
gast==0.5.3
gitdb==4.0.9
gitpython==3.1.27
grpcio==1.47.0
gym==0.17.2
h5py==3.7.0
importlib-metadata==4.12.0
joblib==1.1.0
keras-applications==1.0.8
keras-preprocessing==1.1.2
kiwisolver==1.4.3
markdown==3.3.7
matplotlib==3.0.3
memory-profiler==0.60.0
mock==4.0.3
mpi4py==3.1.3
munch==2.5.1.dev12
numpy==1.18.5
opencv-python==4.6.0.66
pandas==1.0.5
progressbar2==4.0.0
protobuf==3.20.0
psutil==5.9.1
py-cpuinfo==8.0.0
pygame==1.9.5
pyglet==1.5.0
pymongo==4.1.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.1
sacred==0.7.4
scipy==1.5.0
seaborn
six==1.16.0
smmap==5.0.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
tensorflow-io-gcs-filesystem==0.26.0
tqdm==4.64.0
typing-extensions==4.3.0
werkzeug==2.1.2
wrapt==1.14.1
zipp==3.8.0